# Generated by Django 3.2.4 on 2021-07-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_memant_heiza'),
    ]

    operations = [
        migrations.AddField(
            model_name='memant',
            name='heiza_email',
            field=models.EmailField(default='nonone@none.com', max_length=254),
        ),
    ]
