# Generated by Django 3.2.4 on 2021-06-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heiza', models.IntegerField(default=0, max_length=100)),
                ('heiza_text', models.TextField(blank=True, max_length=100, null=True)),
                ('heiza_answer', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
